name: Azure App Service Backend CI/CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_deploy_backend:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Build (if needed)
        run: |
          cd backend
          if [ -f package.json ] && grep -q '"build"' package.json; then npm run build; fi

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: limos-rental-api # <-- Updated to your Azure App Service name
          slot-name: production
          package: ./backend
        env:
          MY_POS_PRIVATE_KEY: ${{ secrets.MY_POS_PRIVATE_KEY }}
          # Add other secrets as needed
