name: Azure Static Web Apps CI/CD 

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment:
      name: "Production"
      url: https://nice-bay-07b756a03.6.azurestaticapps.net
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean workspace
        run: |
          rm -rf node_modules dist .env
          echo "Cleaned workspace"

      - name: Install dependencies
        run: |
          npm ci --no-audit
          echo "Node modules installed successfully"

      - name: Add build timestamp
        run: |
          echo "VITE_BUILD_TIME=$(date +%s)" >> .env
          echo "VITE_DEPLOY_ID=${{ github.run_id }}" >> .env
          echo "Build information added to environment"

      - name: Build
        run: |
          npm run build
          echo "<!-- Build: $(date) -->" >> dist/index.html
          echo "<!-- Deploy ID: ${{ github.run_id }} -->" >> dist/index.html
          find dist -type f | wc -l
          du -sh dist
          echo "Build completed successfully"

      - name: Prepare deployment
        run: |
          cd dist
          find . -type f -name "*.map" -delete
          echo "Deployment preparation completed"

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_BAY_07B756A03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"
          skip_app_build: true
          production_branch: "master"
          deployment_environment: "Production"
          force_deployment: true

      - name: Clear preview environments
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Cleaning up preview environments..."
          curl -X DELETE -H "Authorization: Bearer ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_BAY_07B756A03 }}" "https://management.azure.com/subscriptions/${{ vars.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ vars.AZURE_RESOURCE_GROUP }}/providers/Microsoft.Web/staticSites/${{ vars.AZURE_STATIC_SITE_NAME }}/builds?api-version=2019-12-01-preview"

      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to propagate..."
          sleep 45
          curl -I https://nice-bay-07b756a03.6.azurestaticapps.net || true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_BAY_07B756A03 }}
          action: "close"
