name: Azure Static Web Apps CI/CD 

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean workspace
        run: |
          rm -rf node_modules
          rm -rf dist
          rm -rf .env
          echo "Cleaned workspace"

      - name: Clean install dependencies
        run: |
          npm ci
          echo "Node modules installed successfully"

      - name: Add build timestamp
        run: |
          echo "VITE_BUILD_TIME=$(date +%s)" >> .env
          echo "VITE_DEPLOY_ID=${{ github.run_id }}" >> .env
          echo "Build information added to environment"

      - name: Build
        run: |
          npm run build
          echo "<!-- Build: $(date) -->" >> dist/index.html
          echo "<!-- Deploy ID: ${{ github.run_id }} -->" >> dist/index.html
          echo "Build completed successfully"

      - name: List build output
        run: |
          ls -la dist/
          cat dist/index.html | tail -n 5
          echo "Build output listed"

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_BAY_07B756A03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"
          skip_app_build: true
          production_branch: "master"
          deployment_environment: production
          force_deployment: true

      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to propagate..."
          sleep 30
          curl -I https://nice-bay-07b756a03.6.azurestaticapps.net

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_BAY_07B756A03 }}
          action: "close"
