name: Deploy Backend API to Azure

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      run: cd backend && npm ci

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'limos-rental-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: backend

    - name: Configure App Settings
      uses: azure/appservice-settings@v1
      with:
        app-name: 'limos-rental-api'
        app-settings-json: '[
          {
            "name": "CORS_ORIGIN",
            "value": "https://www.elitewaylimo.ch"
          },
          {
            "name": "COMMUNICATION_CONNECTION_STRING",
            "value": "${{ secrets.COMMUNICATION_CONNECTION_STRING }}"
          },
          {
            "name": "EMAIL_FROM",
            "value": "noreply@elitewaylimo.ch"
          },
          {
            "name": "ADMIN_EMAIL",
            "value": "aleksandarpantic98@gmail.com"
          },
          {
            "name": "WEBSITE_NODE_DEFAULT_VERSION",
            "value": "~18"
          },
          {
            "name": "FRONTEND_URL",
            "value": "https://www.elitewaylimo.ch"
          }
        ]'
        mask-inputs: true

    # Health check after deployment
    - name: Health check
      run: |
        echo "Waiting for service to start..."
        sleep 30
        response=$(curl -s -o /dev/null -w "%{http_code}" https://limos-rental-api.azurewebsites.net/health)
        if [ "$response" != "200" ]; then
          echo "Health check failed with status $response"
          exit 1
        fi